export const DOG_BREEDS: string[] = [
  // Indian/South Asian breeds
  "Indian Pariah Dog",
  "Mudhol Hound",
  "Rajapalayam",
  "Chippiparai",
  "Kombai",
  "Kanni",
  "Bakharwal",
  "Gaddi Kutta",
  "Rampur Greyhound",
  "Jonangi",
  "Pandikona",
  "Mahratta Greyhound",

  // Common breeds in India (popular pets)
  "Labrador Retriever",
  "German Shepherd",
  "Golden Retriever",
  "Beagle",
  "Pomeranian",
  "Shih Tzu",
  "Pug",
  "Dachshund",
  "Rottweiler",
  "Dobermann",
  "Great Dane",
  "Cocker Spaniel",
  "Boxer",
  "Dalmatian",
  "Lhasa Apso",
  "Maltese",
  "Siberian Husky",
  "Alaskan Malamute",
  "Border Collie",
  "Australian Shepherd",
  "Saint Bernard",
  "Bulldog",
  "French Bulldog",
  "Miniature Pinscher",
  "Chihuahua",
  "Bichon Frise",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Yorkshire Terrier",
  "Miniature Schnauzer",
  "Bull Terrier",
  "Staffordshire Bull Terrier",
  "Basset Hound",
  "Bloodhound",
  "Weimaraner",
  "Vizsla",
  "Irish Setter",
  "English Setter",
  "Gordon Setter",
  "Pointer",
  "Bracco Italiano",
  "Springer Spaniel",
  "Cavalier King Charles Spaniel",
  "Borzoi",
  "Afghan Hound",
  "Saluki",
  "Greyhound",
  "Whippet",
  "Italian Greyhound",
  "Basenji",
  "Rhodesian Ridgeback",
  "Chow Chow",
  "Akita",
  "Shiba Inu",
  "Samoyed",
  "Newfoundland",
  "Bernese Mountain Dog",
  "Swiss Mountain Dog",
  "Bouvier des Flandres",
  "Belgian Malinois",
  "Belgian Tervuren",
  "Cane Corso",
  "Mastiff",
  "Bullmastiff",
  "Neapolitan Mastiff",
  "Tibetan Mastiff",
  "Tibetan Spaniel",
  "Tibetan Terrier",
  "Papillon",
  "Pekinese",
  "Japanese Chin",
  "Brussels Griffon",
  "Havanese",
  "Toy Fox Terrier",
  "Cairn Terrier",
  "West Highland White Terrier",
  "Scottish Terrier",
  "Jack Russell Terrier",
  "Parson Russell Terrier",
  "Fox Terrier",
  "Airedale Terrier",
  "Irish Terrier",
  "Kerry Blue Terrier",
  "Soft Coated Wheaten Terrier",
  "Shar Pei",
  "Keeshond",
  "Norwegian Elkhound",
  "Finnish Spitz",
  "Icelandic Sheepdog",
  "Shetland Sheepdog",
  "Collie (Rough)",
  "Collie (Smooth)",
  "Old English Sheepdog",
  "Briard",
  "Polish Lowland Sheepdog",
  "Puli",
  "Komondor",
  "Hungarian Vizsla",
  "Catahoula Leopard Dog",
  "American Pit Bull Terrier",
  "American Staffordshire Terrier",
  "Miniature Bull Terrier",

  // Mixed / Other
  "Mixed Breed",
  "Indie",
]

export const CAT_BREEDS: string[] = [
  // Indian / Common in India
  "Indian Domestic Cat",
  "Indian Billi (Street Cat)",

  // Popular breeds in India
  "Persian",
  "Himalayan",
  "Siamese",
  "Maine Coon",
  "British Shorthair",
  "Scottish Fold",
  "Ragdoll",
  "Bengal",
  "Abyssinian",
  "Burmese",
  "Russian Blue",
  "Norwegian Forest Cat",
  "Birman",
  "Tonkinese",
  "Devon Rex",
  "Cornish Rex",
  "Sphinx (Hairless)",
  "American Shorthair",
  "Exotic Shorthair",
  "Oriental Shorthair",
  "Balinese",
  "Javanese",
  "Turkish Angora",
  "Turkish Van",
  "Chartreux",
  "Manx",
  "Japanese Bobtail",
  "Singapura",
  "Somali",
  "Selkirk Rex",
  "LaPerm",
  "Ocicat",
  "Egyptian Mau",
  "Bombay",
  "Havana Brown",
  "Colorpoint Shorthair",
  "Cymric",
  "Siberian",
  "Ragamuffin",
  "Savannah",
  "Chausie",
  "Pixiebob",
  "Munchkin",
  "Scottish Straight",
  "Burmilla",
  "Tiffanie",
  "Asian",

  // Mixed / Other
  "Mixed Breed",
  "Domestic",
]
